algoritmo "Area do Triangulo"
//Calcular a área do triangulo
//obter valor da base e da altura do triangulo
//calcular o valor da área = base x altura / 2
//imprimir o valor da área
var
   baset, alturat, areat: real
inicio
      Escreva ("Insira o valor da BASE do Triangulo: ")
      Leia (baset)
      Escreva ("Insira o valor da ALTURA do Triangulo: ")
      Leia (alturat)
      areat <- (baset*alturat) / 2
      Escreva ("A AREA do Triangulo é: ",areat)
fimalgoritmo
